### ISSUE TITLE
Realms

### ISSUE THREAD

**Issue by SlightlyPeckish** [mircokroon/minecraft-world-downloader#132] opened 2021-03-15 23:30 UTC
The ability to download worlds from Realms would be nice but I'm not sure how that would be implemented

**Comment by mircokroon** [comment] 2021-03-16 10:34
I believe this already works, you just need to find the IP and port of the realm. I don't have access to any realms myself so I can't check exactly how to do it, but I think you can find it by enabling log output in the launcher, and then looking for a line that reads `Connecting to [address], [port]` when you connect to the realm. Then you put this in the downloader and connect to the proxy through the regular Multiplayer menu. 

![image](https://user-images.githubusercontent.com/23699979/111294824-020ce200-864b-11eb-885c-ecaadda52d40.png)

**Comment by SlightlyPeckish** [comment] 2021-03-16 17:22
Just gave it a go and the only thing that shows up is this
`Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'`

For reference I attempted to join hypixel and it did display this: 
`Connecting to mc.hypixel.net, 25565`

**Comment by mircokroon** [comment] 2021-03-16 23:12
I guess it's a little bit harder for realms, you need to either use the API or something like Wireshark to find it. I spent a bit of time today building a UI where you can see your realms, and then select it to be used in the downloader. Apparently if you have not joined it in a bit it needs to start first, so then it can take a while for the IP to be loaded. 

Pre-release here: https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.13.3 . Still needs a bit of polish before I'll fully release it.

If you could give it a try and see if this works for you, that'd be great.

**Comment by SlightlyPeckish** [comment] 2021-03-17 01:20
I don't know if I'm doing something wrong but it just seems to stay stuck loading (waited a good 5-10 mins to see if it would load)

https://i.imgur.com/rAbNhqo.png

**Comment by mircokroon** [comment] 2021-03-17 16:25
Did you start Minecraft first? It's possible your credentials were expired so it couldn't retrieve the list. (It also doesn't use the manual authentication details currently)

**Comment by SlightlyPeckish** [comment] 2021-03-17 16:26
Yeah I even logged into the realm during one of the attempts

**Comment by mircokroon** [comment] 2021-03-17 16:51
Added some better error handling: https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.13.3b

Does it tell you anything useful?

**Comment by SlightlyPeckish** [comment] 2021-03-17 18:22
The error is just repeating this:
`Mar 17, 2021 6:19:30 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 8.0.281`

**Comment by mircokroon** [comment] 2021-03-17 18:39
Ah, I didn't test it on 1.8, sorry.

Hopefully last revision: https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.13.3c

**Comment by SlightlyPeckish** [comment] 2021-03-17 19:13
The realm showed up immediately but upon trying to join the localhost it gave this error
` Cannot connect to [IP was here]. The server may be down or on a different address. (java.net.ConnectException)`
idk if I should be sharing the ip so I blanked it out

**Comment by mircokroon** [comment] 2021-03-17 19:36
Some progress at least. Realms seem to change IP whenever they get put to sleep and wake up again (i.e. nobody played on it for some minutes), so if there is some time in between requesting the IP and joining I guess that might happen. 

Did it fill in both the IP and port? If so I'm not sure what could have gone wrong. Does it still do that if you try again?

**Comment by SlightlyPeckish** [comment] 2021-03-17 20:01
Just checked another couple times and I'm getting the same error in world downloader

This is new though https://i.imgur.com/cqA7cUZ.png

**Comment by mircokroon** [comment] 2021-03-17 20:06
Just to confirm, did you click the "Select" button after the IP was requested? This actually fills it in in the connection menu

**Comment by SlightlyPeckish** [comment] 2021-03-17 20:08
Yeah It took me back to the connection tab and then I pressed start

**Comment by mircokroon** [comment] 2021-03-17 20:11
Can you try connecting directly to the IP and port through the multiplayer menu?

**Comment by SlightlyPeckish** [comment] 2021-03-17 20:24
I'm able to join the realm through the IP directly in the multiplayer tab but when trying to join localhost after starting world downloader it says there's an error (same as before) and it times out in minecraft

**Comment by mircokroon** [comment] 2021-03-18 09:52
I only managed to reproduce this once, but then it worked fine the next time (the server just seems to have closed in between requesting the IP and connecting).

 I made the URL handling slightly less naive and made it so that the address field is not focused when the server is selected (so hopefully it's less likely to accidentally type a space or something). Hopefully one of these was causing problems

https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.13.3d

**Comment by SlightlyPeckish** [comment] 2021-03-18 16:26
I'm sorry idk why this still isn't working 
It's timing out in minecraft and giving this error in the downloader
`Cannot connect to ip was here. The server may be down or on a different address. (java.net.ConnectException)`

**Comment by SlightlyPeckish** [comment] 2021-03-18 16:28
I tried again using localhost and the port from the downloader and I got this error
https://i.imgur.com/RBMDG5S.png
also just tried the original ip and port that got requested and I can join the server fine so the ip appears to have not changed but it just times out connecting to the localhost/giving that error

**Comment by mircokroon** [comment] 2021-03-18 16:51
Just to confirm, here's what the process looks like for me currently (which seems to always work): 
- Start Minecraft
- Start World Downloader
- Open Realms tab (in downloader), Request IP -> Select
- Now the Connection tab shows some form of IP and Port, e.g.:
![image](https://user-images.githubusercontent.com/23699979/111664811-73e35800-8812-11eb-8635-8f7a9873840a.png)

- Click "Start"
- In Minecraft, connect to `localhost` (or `localhost:25565`)

Are you doing the same thing or is there something different?

**Comment by SlightlyPeckish** [comment] 2021-03-18 16:56
I'm doing exactly that

**Comment by mircokroon** [comment] 2021-03-18 17:03
Very strange. Is there anything unusual about your set-up? e.g. are you using a custom launcher?

Also, which version of Minecraft are you using?

**Comment by SlightlyPeckish** [comment] 2021-03-18 17:11
I'm using the default launcher and I've tried on both vanilla 1.16.5 and optifine 1.16.5

**Comment by mircokroon** [comment] 2021-03-18 17:13
And the downloader works fine for non-realm worlds?

**Comment by mircokroon** [comment] 2021-03-18 17:19
I think I've managed to reproduce it now, I'll see if I can find the cause and fix it.

**Comment by mircokroon** [comment] 2021-03-18 17:35
So apparently the port of the realm did not get set correctly if the value of field was the default, but if there was a different value in there it did. I just never tested it with the value set to the default apparently.

Sorry for all the hassle, it should be all good now:
https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.13.3e

**Comment by SlightlyPeckish** [comment] 2021-03-18 18:09
That worked great thank you for the hard work
I've lost my inventory and my pets aren't my pets anymore but other than that the map is all there and working (which is all I needed) :) might need them some other time but the realms download works 👍

**Comment by mircokroon** [comment] 2021-03-18 21:00
Yeah player inventories aren't saved, block inventories are (e.g. chests and barrels). I guess you can fix the pets with `/entitydata` or something, not sure exactly.

Glad to hear that it's working well. This turned out to be quite a valuable addition to the downloader as well I think.

**Closed** 2021-03-18 21:01 UTC
Labels: enhancement
