### ISSUE TITLE
'Exception in thread "Chunk Parser Service"'

### ISSUE THREAD

**Issue by Wrcts** [mircokroon/minecraft-world-downloader#583] opened 2023-08-13 23:50 UTC
**Describe the bug**
Upon joining the localhost, everything seems to be as expected at first, but when moving around, none of the chunks being loaded get downloaded. On the downloader's map, the player and camera are at the correct location and the player icon are moving as I walk around.

**Steps to reproduce**
The bug appeared after I had saved a significant portion of the world, with the world folder getting to around 1.3 GB, and the saved area spanning tens of thousands of blocks at its widest point. I don't know exactly how to read the error output, but it could be related to that.

**Log output**
```
Exception in thread "Chunk Parser Service" Exception in thread "Chunk Parser Service" java.lang.OutOfMemoryError: Java heap space
	at org.apache.commons.io.IOUtils.byteArray(IOUtils.java:338)
	at org.apache.commons.io.output.AbstractByteArrayOutputStream.toByteArrayImpl(AbstractByteArrayOutputStream.java:365)
	at org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.toByteArray(UnsynchronizedByteArrayOutputStream.java:147)
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:2406)
	at game.data.region.McaFile.readFile(McaFile.java:190)
	at game.data.region.McaFile.<init>(McaFile.java:68)
	at game.data.region.McaFile.<init>(McaFile.java:77)
	at game.data.region.Region.<init>(Region.java:43)
	at game.data.region.Region.<clinit>(Region.java:22)
	at game.data.WorldManager.getChunk(WorldManager.java:302)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:121)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at game.data.chunk.ChunkFactory$$Lambda$1010/0x0000000801091d10.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "Chunk Parser Service" Exception in thread "Chunk Parser Service" java.lang.NoClassDefFoundError: Could not initialize class game.data.region.Region
	at game.data.WorldManager.getChunk(WorldManager.java:302)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:121)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at        
...

```
It proceeds to repeat everything past the "at game.data.WorldManager.getChunk(WorldManager.java:302)" line, with some "Exception in thread "Chunk Parser Service" java.lang.NoClassDefFoundError: Could not initialize class game.data.region.Region" sprinkled in too. As said before, I cannot really read the error, but the "java.lang.OutOfMemoryError" bit confuses me because my computer has 32 gigs of ram.

(I just wanna quickly say that, mircokroon, you have really created an amazing piece of software here, and you deserve to be commended for it.)

**Version**
 - Game: Minecraft 1.12.2
 - Downloader: latest

**Comment by Adeekonn** [comment] 2023-08-15 07:30
Facing the same bug.

**Comment by mircokroon** [comment] 2023-08-20 12:05
Does this also happen when restarting and continuing to download the same world or was it a one-time thing?

**Comment by Wrcts** [comment] 2023-08-20 14:08
> Does this also happen when restarting and continuing to download the same world or was it a one-time thing?

Yep, it continues

**Comment by mircokroon** [comment] 2023-08-22 13:11
Does it happen immediately upon starting the downloader or after some time?

**Comment by Wrcts** [comment] 2023-08-22 14:27
> Does it happen immediately upon starting the downloader or after some time?

As soon as the downloader would've started saving chunks

**Comment by mircokroon** [comment] 2023-08-22 17:26
Interesting, is it possible to send the downloaded world so I can see if there's anything unsual about it?

**Comment by Wrcts** [comment] 2023-08-22 18:36
> Interesting, is it possible to send the downloaded world so I can see if there's anything unsual about it?

https://drive.google.com/file/d/1-tMSPdgB1lM5cUpIa12NhimMuoS-mw1w/view?usp=sharing Here

**Comment by mircokroon** [comment] 2023-08-22 19:31
Can you try deleting or renaming the `image-cache` folder and seeing if that solves the issue?

**Comment by Wrcts** [comment] 2023-08-22 19:39
> Can you try deleting or renaming the `image-cache` folder and seeing if that solves the issue?

Yep, that fixed it. I'm guessing that the program can't handle having all those images loaded for the map?

**Comment by mircokroon** [comment] 2023-08-22 19:47
Apparently, looks like it uses about ~1 MB per region but temporarily uses a lot more while loading them.

I think running with `-Xmx4g` (or more) would also work in this case, I can't reproduce the crash myself just noticed how much memory it was using. 

I'll look into optimizing how the images are handled since this is clearly not a good method for large downloads

**Comment by Wrcts** [comment] 2023-08-22 19:51
> Apparently, looks like it uses about ~1 MB per region but temporarily uses a lot more while loading them.
> 
> I think running with `-Xmx4g` (or more) would also work in this case, I can't reproduce the crash myself just noticed how much memory it was using.
> 
> I'll look into optimizing how the images are handled since this is clearly not a good method for large downloads

Interesting, should I close the issue?

**Comment by mircokroon** [comment] 2023-08-22 19:53
I'll see if I can properly fix the issue and close it with a PR then

**Comment by mircokroon** [comment] 2023-08-22 23:31
Made a [pre-release](https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.17.5_pre) for fixing the issue properly if you want to try, very much needs some further work but at least seems a lot better than before

**Comment by Wrcts** [comment] 2023-08-27 00:26
> Made a [pre-release](https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.17.5_pre) for fixing the issue properly if you want to try, very much needs some further work but at least seems a lot better than before

yep, that fixed it.

**Closed** 2023-08-27 19:43 UTC
Labels: bug
