### ISSUE TITLE
1.16.2 - Chunk could not be parsed, VarInt lacks bytes! We may be out of sync now

### ISSUE THREAD

**Issue by Malsententia** [mircokroon/minecraft-world-downloader#61] opened 2020-08-24 16:05 UTC
I've been trying to connect to a 1.16.2 server, nothing special about it, works fine with vanilla client, works fine through the bridge but the downloading fails and I am getting the following error:

`Login success: XXXXXXXXXXXXXXX logged in with uuid abcd1234abcd1234abcd1234abcd1234abcd1234
Using protocol of game version 1.16.0 (751)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 9 out of bounds for byte[6]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:79)
        at packets.DataTypeProvider.readInt(DataTypeProvider.java:69)
        at packets.builder.ClientBoundGamePacketBuilder.lambda$new$6(ClientBoundGamePacketBuilder.java:77)
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)
        at packets.DataReader.readPackets(DataReader.java:161)
        at packets.DataReader.pushData(DataReader.java:116)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:113)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:110)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.run(ProxyServer.java:68)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 9 out of bounds for byte[6]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:79)
        at packets.DataTypeProvider.readInt(DataTypeProvider.java:69)
        at packets.builder.ClientBoundGamePacketBuilder.lambda$new$6(ClientBoundGamePacketBuilder.java:77)
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)
        at packets.DataReader.readPackets(DataReader.java:161)
        at packets.DataReader.pushData(DataReader.java:116)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:113)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:110)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.run(ProxyServer.java:68)
java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:65)
        at game.data.chunk.Chunk.readChunkColumn(Chunk.java:129)
        at game.data.chunk.Chunk.parse(Chunk.java:269)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:204)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:154)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:65)
        at game.data.chunk.Chunk.readChunkColumn(Chunk.java:129)
        at game.data.chunk.Chunk.parse(Chunk.java:269)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:204)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:154)
Chunk could not be parsed!
java.lang.RuntimeException: VarInt lacks bytes! We may be out of sync now.
        at packets.DataReader.readVarInt(DataReader.java:68)
        at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:100)
        at game.data.chunk.palette.Palette.readPalette(Palette.java:69)
        at game.data.chunk.Chunk.readChunkColumn(Chunk.java:131)
        at game.data.chunk.Chunk.parse(Chunk.java:269)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:204)
        at game.data.chunk.ChunkFactory.run(ChunkFactory.java:154)
Chunk could not be parsed!`

**Comment by mircokroon** [comment] 2020-08-25 13:40
Duplicate of #54

**Closed by mircokroon** 2020-08-25 13:40 UTC
Labels: duplicate
