### ISSUE TITLE
what does this mean?

### ISSUE THREAD

**Issue by 15695** [mircokroon/minecraft-world-downloader#72] opened 2020-09-17 16:44 UTC
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by mircokroon** [comment] 2020-09-17 17:22
Duplicate of #29

**Closed by mircokroon** 2020-09-17 17:22 UTC
