### ISSUE TITLE
"Cannot connect to server"

### ISSUE THREAD

**Issue by Juan16236123** [mircokroon/minecraft-world-downloader#60] opened 2020-08-22 05:04 UTC
Hello, every time I try to download a map, it says "Cannot connect to %IP%. The server may be down or on a different address."

I know I put the correct address, and I even tried other servers and they didn't work! This issue occurs when I try to connect to "localhost" and "localhost:25565"

Terminal Code:
_java -jar world-downloader.jar -s hypixel.net_
(hypixel.net is used as an example!)

System: Mac OS (Big Sur)
JDK: Java 9

_(Everything works completely fine, except after I put in my Access Token in and logon, it gives me this error)_

**Comment by mircokroon** [comment] 2020-08-25 13:37
You can check if an SRV record exists for the server, most likely it's related to that. 

Not sure about the authentication thing, it's most likely one of these: https://wiki.vg/Authentication#Errors

**Comment by mircokroon** [comment] 2020-10-08 18:10
No updates in a while, and can't reproduce so I'll close it

**Closed by mircokroon** 2020-10-08 18:10 UTC
Labels: question
