### ISSUE TITLE
Java error (on newest java)

### ISSUE THREAD

**Issue by fym35** [mircokroon/minecraft-world-downloader#102] opened 2021-02-03 10:23 UTC
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by mircokroon** [comment] 2021-02-03 20:52
Duplicate of #29 

Probably you have multiple Java versions installed and you're accidentally running it on an older one.

**Closed by mircokroon** 2021-02-03 20:52 UTC

**Comment by fym35** [comment] 2021-02-04 08:06
thanks , when i uninstalled old java it works
