### ISSUE TITLE
Does world downloader work for 1.17

### ISSUE THREAD

**Issue by Tokaroi** [mircokroon/minecraft-world-downloader#209] opened 2021-09-07 20:25 UTC
I was trying to get world downloader to worlk on a new smp sever for 1.17.1 for my base but every time i try to use it it gives a error.
So does it work and if not when will it be updated for 1.17.1

**Comment by mircokroon** [comment] 2021-09-07 20:49
What is the error you're getting?

**Comment by mircokroon** [comment] 2021-09-08 21:44
Can you try the latest version? Might just have been #189

**Comment by LarcekGiglamesh** [comment] 2021-09-23 10:27
same issue here. trying to connect to a **1.17.1** server by **localhost:25565** or just **localhost** fails. 

```
Authentication details are retrieved from the Minecraft game directly. Make sure that the game is running.
If you have a username set in the authentication tab, ensure that it matches the one you are trying to connect with.
If you are in an environment where this does not work, please set the correct username and token in the authentication tab.
See https://github.com/mircokroon/minecraft-world-downloader/wiki/Authentication for more details.

javax.security.sasl.AuthenticationException: Cannot get valid authentication details. [Caused by javax.security.sasl.AuthenticationException: Cannot find authentication details.]
        at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:40)
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: javax.security.sasl.AuthenticationException: Cannot find authentication details.
        at proxy.auth.AuthDetailsManager.getAuthDetails(AuthDetailsManager.java:47)
        at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:37)
        ... 14 more
Server probably disconnected. Waiting for new connection...
```

running v1.14.6 of world-downloader using an absolute path since i have multiple instances of java installed.
`D:\Games\Minecraft World Downloader>"C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot\bin\java.exe" -jar world-downloader.jar`
GUI opens fine, i have no Authentifcations set since i cannot grab the accessToken from the vanilla minecraft `.minecraft\launcher_accounts.json` file, it just stays empty. Possibly since i have yet to migrate my Mojang into Microsoft account?

**Comment by mircokroon** [comment] 2021-09-23 11:56
Are you using Windows? If so, can you confirm that there is a `javaw.exe` process active while Minecraft is open?

**Comment by LarcekGiglamesh** [comment] 2021-09-23 12:45
Yes, i'm running Win10 Home on 21H1
i'm running openjdk with the command mentioned above so i didn't expect it, but i still gave it a look. 

![grafik](https://user-images.githubusercontent.com/19149222/134508783-42e807fe-ae43-423d-8473-81c814cae15f.png)

no javaw here

**Comment by mircokroon** [comment] 2021-09-23 12:59
Interesting, so I guess it sometimes uses `java.exe` instead. I'll change it to work with both.

Out of interest, are you using a custom launcher to start Minecraft? Could be that MultiMC or something uses `java.exe` instead.

**Comment by mircokroon** [comment] 2021-09-23 13:07
Can you try on the latest release?
https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.14.7

**Comment by LarcekGiglamesh** [comment] 2021-09-23 13:45
i have yet to check it on SP, but i was able to login onto the server in question now. console and gui are looking good!

![grafik](https://user-images.githubusercontent.com/19149222/134518098-f0f8ed5e-b909-413b-8c75-4264df45e5b3.png)
![grafik](https://user-images.githubusercontent.com/19149222/134518290-f3bf247b-0c88-435f-9037-86aa70235a27.png)

personally prefer to use GDLauncher but since your Wiki suggested to use username as well as accessToken as flags i also tried the vanilla launcher.

**Comment by LarcekGiglamesh** [comment] 2021-09-23 14:07
i can confirm the downloaded world loading in fine. seems enderchest contents are too dynamic to be stored, but that can be manually fixed. thanks for the fast responses. :)

**Comment by mircokroon** [comment] 2021-09-23 15:41
Great, so I guess the issue might be other launchers not using `javaw.exe` then. I'll close this since I assume it's resolved for everyone.

**Closed by mircokroon** 2021-09-23 15:41 UTC
Labels: question
