### ISSUE TITLE
Still not saving chests/inventory consistently

### ISSUE THREAD

**Issue by daiiwulf** [mircokroon/minecraft-world-downloader#80] opened 2020-10-14 08:48 UTC
I've tried newer versions, 1.13.2, 1.16.2 and 1.16.3, and none of them seem to be able to save chest contents consistently. 
With 1.13.2, once done saving the map data and copying it into a singleplayer, the game outright crashes on load.
with 1.16.2 and 1.16.3, sometimes the chest data saves, sometimes it does not. A lot of the time the chest entities are not being drawn in game, or it only saves half of the chest contents.

I don't have any debug info, the crashes dont produce an error, and with 1.16.x, the chests just don't have contents half the time. Could it be with how the chests are placed in world? Regular chests next to trapped chests?

**Comment by daiiwulf** [comment] 2020-10-15 01:16
I've done some further testing with both 1.16.2 and 1.16.3, 1.13.2 and 1.14.2 along with app versions 1.6 and 1.7.

1.13, 1.14 generates invalid world data, when you copy it to an SP world, the game crashes. on loading the map data in mcedit, theres 1000s of block data errors, happens with both 1.6 and 1.7

mc1.16.2 and .3, both 1.6 and 1.7 will save world data, but chest entities appear to not get saved. Often, it is the Trapped Chest (both single and double) that gets invalid entity data. Shulkers are a 50/50. Sometimes they do, sometimes they dont. Regular chests and double chests also often fail to either save their block data, and always fail to save inventory.

**Comment by mircokroon** [comment] 2020-10-15 10:19
Thanks, I'll go see if I can sort it out.

**Comment by mircokroon** [comment] 2020-10-15 19:09
I think I've fixed all of the above now. One issue was related to opening inventories after the chunk had already been saved. 

1.13 and 1.14 work for me now, I did have crashing in 1.13 at some point so either that is now fixed or it's something inconsistent. I think technically newer versions aren't supported by mcedit so I don't know how reliable that is.

**Comment by daiiwulf** [comment] 2020-10-16 00:07
Alright, I've given another go with the latest version. Still trouble. 1.16.2 does save the chest entites correctly (no more invisible/invalid entities) but doesnt save any contents.

1.12.2 does save contents, sort of. It worked for a handful of chests/shulkers, then stopped. The following error string was produced:

`Using protocol of game version 1.12.2 (340)
java.lang.NullPointerException
        at game.data.chunk.palette.BlockState.hasProperty(BlockState.java:40)
        at game.data.container.ContainerManager.closeWindow(ContainerManager.java:78)
        at game.data.container.ContainerManager.closeWindow(ContainerManager.java:64)
        at packets.builder.ServerBoundGamePacketBuilder.lambda$new$2(ServerBoundGamePacketBuilder.java:40)
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)
        at packets.DataReader.readPackets(DataReader.java:161)
        at packets.DataReader.pushData(DataReader.java:116)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:100)
        at proxy.ProxyServer.attempt(ProxyServer.java:165)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:97)
        at java.base/java.lang.Thread.run(Thread.java:830)
Unable to write chunk -431, 479
java.lang.NullPointerException
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:352)
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:326)
        at se.llbit.nbt.StringTag.write(StringTag.java:57)
        at se.llbit.nbt.StringTag.write(StringTag.java:53)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.ListTag.write(ListTag.java:71)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.ListTag.write(ListTag.java:71)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:51)
        at game.data.region.Region.lambda$toFile$0(Region.java:115)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)
        at game.data.region.Region.toFile(Region.java:96)
        at game.data.WorldManager.save(WorldManager.java:381)
        at game.data.WorldManager.run(WorldManager.java:358)
Unable to write chunk -431, 479
java.lang.NullPointerException
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:352)
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:326)
        at se.llbit.nbt.StringTag.write(StringTag.java:57)
        at se.llbit.nbt.StringTag.write(StringTag.java:53)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.ListTag.write(ListTag.java:71)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.ListTag.write(ListTag.java:71)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:51)
        at game.data.region.Region.lambda$toFile$0(Region.java:115)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)
        at game.data.region.Region.toFile(Region.java:96)
        at game.data.WorldManager.save(WorldManager.java:381)
        at game.data.WorldManager.run(WorldManager.java:358)
Unable to write chunk -431, 479
java.lang.NullPointerException
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:352)
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:326)
        at se.llbit.nbt.StringTag.write(StringTag.java:57)
        at se.llbit.nbt.StringTag.write(StringTag.java:53)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.ListTag.write(ListTag.java:71)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.ListTag.write(ListTag.java:71)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:51)
        at game.data.region.Region.lambda$toFile$0(Region.java:115)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)
        at game.data.region.Region.toFile(Region.java:96)
        at game.data.WorldManager.save(WorldManager.java:381)
        at game.data.WorldManager.run(WorldManager.java:358)
Unable to write chunk -431, 479
java.lang.NullPointerException
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:352)
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:326)
        at se.llbit.nbt.StringTag.write(StringTag.java:57)
        at se.llbit.nbt.StringTag.write(StringTag.java:53)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.ListTag.write(ListTag.java:71)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.ListTag.write(ListTag.java:71)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:51)
        at game.data.region.Region.lambda$toFile$0(Region.java:115)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)
        at game.data.region.Region.toFile(Region.java:96)
        at game.data.WorldManager.save(WorldManager.java:381)
        at game.data.WorldManager.run(WorldManager.java:358)
Pausing`

There was nothing special in the chests that produced this error, just normal game blocks.

**Comment by mircokroon** [comment] 2020-10-16 09:53
I can't reproduce either of these. Can you provide some steps / screenshots of how you can get this to happen?

You do need to open every chest for it to be saved, and reloading a chunk after a chest was saved will currently cause it to be emptied again.

**Comment by mircokroon** [comment] 2020-10-16 10:38
I tried to fix the issue from 1.12.2, although I can't reproduce it so I can't really verify that it's fixed. Also made it so that reloading a chunk doesn't clear inventories because it was definitely a bit annoying. (Doesn't work when restarting the download yet, only within one session).

**Comment by daiiwulf** [comment] 2020-10-16 23:40
The clearing chests on chunk reload looks to have been what was causing the issue with inventories not saving.

I have now tested the latest built against 1.12.2 and 1.16.2 a with almost full success.

On 1.12.2, chests are saving and keeping inventories through check reloading as I move around the area to open other chests. There is a minor issue in that it looks like coal (the item, not ore or block) is not saving? But everything else looks to be working fine.

I did get another one of those NullPointerException errors while testing under MC client version 1.12.2:

```
java.lang.NullPointerException
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:352)
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:326)
        at se.llbit.nbt.StringTag.write(StringTag.java:57)
        at se.llbit.nbt.StringTag.write(StringTag.java:53)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.ListTag.write(ListTag.java:71)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.ListTag.write(ListTag.java:71)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
        at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
        at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:51)
        at game.data.region.Region.lambda$toFile$0(Region.java:115)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)
        at game.data.region.Region.toFile(Region.java:96)
        at game.data.WorldManager.save(WorldManager.java:381)
        at game.data.WorldManager.run(WorldManager.java:358)
```

Testing under 1.16.2, I got no errors. However, on loading the saved data into an SP world, it appears all trapped double chests are not openable. I can break the chests, get the contents, and then replace them and that seems to fix the issue. I suspect there might be just some unexpected value being saved for a trapped double-chest that is causing this. Single trapped chests also have this issue. 

I've attached a screenshot of the test setup I've been working with.


![2020-10-16_15 46 57](https://user-images.githubusercontent.com/71951513/96322421-d7502c00-0fcd-11eb-9d62-ad69d4738baf.png)

**Comment by mircokroon** [comment] 2020-10-26 20:58
I guess the NullPointer was related to the coal item, for some reason it only recognized charcoal. I guess I messed that up when making the list of items in 1.12.2, luckily thats all automatic for the newer versions.

All my chests open normally, if you'd like to send a world file with broken trapped chests I could check if there is something weird going on with them.

**Comment by daiiwulf** [comment] 2020-10-28 00:59
I tested with client 1.16.2, vanilla server 1.16.2, and latest wdloader app and everything works fine (chests, trapped chests, inventories, shulkers all save just fine. No item frames, but I know that's a different issue already)

But when I test with client 1.16.2 and the server I want to backup my builds from, the trapped chests have the 'cant open' issue. I don't know the server software the server is using.

Attached is the data from the test, this was just a test setup I built. If you drop these files into a sp world, the 'right' hand chests are the trapped chests (same as the previous pic), and you cant open them. But after breaking and placing, they work fine. Theiir inventories are saved fine (just some logs in these)

[1162_1027B.zip](https://github.com/mircokroon/minecraft-world-downloader/files/5448850/1162_1027B.zip)

**Comment by mircokroon** [comment] 2021-02-20 23:12
Not sure why I waited so long to look into this, but anyway, the issue seems to be that some servers send `minecraft:chest` tile entities when the block is `minecraft:trapped_chest`, I changed it now so that the downloader will fix some of the tile entity names.

**Closed** 2021-02-20 23:15 UTC
Labels: bug
