### ISSUE TITLE
Error when joining

### ISSUE THREAD

**Issue by Cerberus22** [mircokroon/minecraft-world-downloader#213] opened 2021-09-12 13:12 UTC
As soon as I join localhost it says an error has occurred in the top left.

Output:
```
java.lang.ArrayIndexOutOfBoundsException: Index -116 out of bounds for length 256
	at game.data.chunk.version.encoder.BlockLocationEncoder_1_16.fetch(BlockLocationEncoder_1_16.java:19)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:126)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:118)
	at game.data.chunk.ChunkSection.getNumericBlockStateAt(ChunkSection.java:114)
	at game.data.chunk.Chunk.getNumericBlockStateAt(Chunk.java:307)
	at game.data.chunk.Chunk.getBlockStateAt(Chunk.java:315)
	at game.data.chunk.Chunk.getBlockStateAt(Chunk.java:311)
	at game.data.chunk.ChunkEntities.addTileEntity(ChunkEntities.java:108)
	at game.data.chunk.ChunkEntities.addTileEntity(ChunkEntities.java:142)
	at game.data.chunk.Chunk.parseTileEntities(Chunk.java:285)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:70)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!

```

**Comment by mircokroon** [comment] 2021-09-13 11:09
This looks like a duplicate of #191 to me

**Closed by mircokroon** 2021-09-13 11:09 UTC
Labels: bug
