### ISSUE TITLE
Lost on how to get the mod working

### ISSUE THREAD

**Issue by ZenFroot** [mircokroon/minecraft-world-downloader#185] opened 2021-07-26 18:03 UTC
I was able to open the .jar file for the world downloader, but once I put in the IP for the server, it takes me to the error message "Connect to address localhost:25565 to start downloading". I left the bar for the server port and the local port blank, and I don't know how to get either of those. 

Please bear with me, I'm new to modding Minecraft and it's a bit confusing for me. 

The screen that I'm left with after putting the server IP in:
<img width="643" alt="Screen Shot 2021-07-14 at 10 00 38 AM" src="https://user-images.githubusercontent.com/87991752/127036807-dd47f01d-64bb-4f57-89b5-65bbdf4e4500.png">

**Comment by mircokroon** [comment] 2021-07-26 18:10
This is not an error message, it's an instruction. If you connect to the server `localhost:25565` in Minecraft, it will connect you to the address you entered and work as intended.

**Comment by ZenFroot** [comment] 2021-07-26 18:15
Tried that, I got this error log: 
java.lang.RuntimeException: Client not authenticated! {
  "error" : "ForbiddenOperationException",
  "path" : "/session/minecraft/join"
}
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:54)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: Packet parsing may have been incorrect! Expected length: 261. Used bytes: 0
	at packets.DataReader.readPackets(DataReader.java:172)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.lang.Thread.run(Thread.java:748)

 java.lang.RuntimeException: Client not authenticated! {
  "error" : "ForbiddenOperationException",
  "path" : "/session/minecraft/join"
}
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:54)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)

 java.lang.RuntimeException: Client not authenticated! {
  "error" : "ForbiddenOperationException",
  "path" : "/session/minecraft/join"
}
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:54)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)

 
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)

**Comment by mircokroon** [comment] 2021-07-26 18:25
Hmm could you try closing all instances of Minecraft and reopening it?

**Comment by ZenFroot** [comment] 2021-07-26 18:33
Tried again, still kept me from connecting. This time though the server icon and text of the server I'm trying to join showed up on the Multiplayer menu on Minecraft.

**Comment by mircokroon** [comment] 2021-07-26 18:41
It's possible there is a compatibility issue since you seem to be using MacOS, I haven't gotten around to verifying some of the recent changes to authentication logic for it.

**Comment by ZenFroot** [comment] 2021-07-26 18:49
Yeah I'm using a Mac to run the jar. Would help if I used one of the more recent releases of the mod? The one I'm trying to use is at least from last month.

**Comment by mircokroon** [comment] 2021-07-26 18:51
Oh, yeah maybe thats the issue then. There were changes to how authentication is handled by the Minecraft launcher recently, the version of a few days ago fixes that (hopefully).

**Comment by mircokroon** [comment] 2021-07-26 22:07
With the same error?

**Comment by JCRamires** [comment] 2021-08-05 02:50
Im also having the same issue.
My account is new, so I had to create it using microsoft.

```
javax.security.sasl.AuthenticationException: Cannot get valid authentication details. [Caused by javax.security.sasl.AuthenticationException: Cannot find authentication details.]
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:40)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.security.sasl.AuthenticationException: Cannot find authentication details.
	at proxy.auth.AuthDetailsManager.getAuthDetails(AuthDetailsManager.java:47)
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:37)
	... 14 more
java.lang.IllegalStateException: Packet parsing may have been incorrect! Expected length: 261. Used bytes: 0
	at packets.DataReader.readPackets(DataReader.java:172)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by mircokroon** [comment] 2021-08-05 11:47
@JCRamires are you on a Mac?

**Comment by MadDog443** [comment] 2021-08-10 05:18
I'm on windows and I have the same issue. I connected via the exe version but it works fine with the jar version.

**Comment by EinfachBen03** [comment] 2021-10-17 00:28
> @JCRamires are you on a Mac?

I am on Windows and am using a Microsoft Account I gues the Token won't work if you are using a Microsoft Account. The switch was such a shitty move...

**Comment by mircokroon** [comment] 2021-10-17 11:36
Well it doesn't have as much to do with the switch as with changing how the auth token is stored locally. Ideally someone with this issue should see if they can find the issue by following [the steps the downloader takes](https://github.com/mircokroon/minecraft-world-downloader/blob/master/src/main/java/proxy/auth/AuthDetailsFromProcess.java) manually to see if anything goes wrong.

**Closed** 2022-06-05 19:06 UTC
Labels: question
